CREATE SEQUENCE classement_categorie_id_seq INCREMENT BY 1 MINVALUE 1 START 1
CREATE TABLE classement_categorie (
    id INT NOT NULL, 
    coureur_id INT NOT NULL, 
    etape_course_id INT NOT NULL, 
    categorie_coureur_id INT NOT NULL, 
    rang INT NOT NULL, 
    point DOUBLE PRECISION NOT NULL, 
    PRIMARY KEY(id)
);
CREATE INDEX IDX_FC95ACC3F4FA42E5 ON classement_categorie (coureur_id)
CREATE INDEX IDX_FC95ACC3740F7C7D ON classement_categorie (etape_course_id)
CREATE INDEX IDX_FC95ACC36A338849 ON classement_categorie (categorie_coureur_id)
ALTER TABLE classement_categorie ADD CONSTRAINT FK_FC95ACC3F4FA42E5 FOREIGN KEY (coureur_id) REFERENCES coureur (id) NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE classement_categorie ADD CONSTRAINT FK_FC95ACC3740F7C7D FOREIGN KEY (etape_course_id) REFERENCES etape_course (id) NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE classement_categorie ADD CONSTRAINT FK_FC95ACC36A338849 FOREIGN KEY (categorie_coureur_id) REFERENCES categorie_coureur (id) NOT DEFERRABLE INITIALLY IMMEDIATE

CREATE SEQUENCE penalite_id_seq INCREMENT BY 1 MINVALUE 1 START 1
CREATE TABLE penalite (
    id INT NOT NULL, 
    etape_course_id INT NOT NULL, 
    temps TIME(0) WITHOUT TIME ZONE NOT NULL, 
    PRIMARY KEY(id)
);
CREATE INDEX IDX_C62D8C5D740F7C7D ON penalite (etape_course_id)
ALTER TABLE penalite ADD CONSTRAINT FK_C62D8C5D740F7C7D FOREIGN KEY (etape_course_id) REFERENCES etape_course (id) NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE penalite ADD equipe_id INT NOT NULL
ALTER TABLE penalite ADD CONSTRAINT FK_C62D8C5D6D861B89 FOREIGN KEY (equipe_id) REFERENCES equipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE
CREATE INDEX IDX_C62D8C5D6D861B89 ON penalite (equipe_id)