CREATE SEQUENCE utilisateur_id_seq INCREMENT BY 1 MINVALUE 1 START 1
CREATE TABLE utilisateur (
    id INT NOT NULL,
    email VARCHAR(180) NOT NULL, 
    roles JSON NOT NULL, 
    password VARCHAR(255) NOT NULL, 
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON utilisateur (email)

CREATE SEQUENCE course_id_seq INCREMENT BY 1 MINVALUE 1 START 1
CREATE TABLE course (
    id INT NOT NULL, 
    nom_course VARCHAR(155) NOT NULL, 
    PRIMARY KEY(id)
);

CREATE SEQUENCE etape_course_id_seq INCREMENT BY 1 MINVALUE 1 START 1
CREATE TABLE etape_course (
    id INT NOT NULL, 
    course_id INT NOT NULL, 
    nbr_coureur INT NOT NULL, 
    nom_etape VARCHAR(155) NOT NULL, 
    longueur DOUBLE PRECISION NOT NULL, 
    PRIMARY KEY(id)
);
CREATE INDEX IDX_A193A906591CC992 ON etape_course (course_id)ALTER TABLE etape_course ADD CONSTRAINT FK_A193A906591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE etape_course ADD depart TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
ALTER TABLE etape_course ALTER COLUMN depart SET NOT NULL

CREATE SEQUENCE point_rang_id_seq INCREMENT BY 1 MINVALUE 1 START 1
CREATE TABLE point_rang (
    id INT NOT NULL, 
    etape_course_id INT NOT NULL, 
    point DOUBLE PRECISION NOT NULL, 
    rang INT NOT NULL, 
    PRIMARY KEY(id)
);
CREATE INDEX IDX_84F43AC740F7C7D ON point_rang (etape_course_id)
ALTER TABLE point_rang ADD CONSTRAINT FK_84F43AC740F7C7D FOREIGN KEY (etape_course_id) REFERENCES etape_course (id) NOT DEFERRABLE INITIALLY IMMEDIATE

CREATE SEQUENCE categorie_coureur_id_seq INCREMENT BY 1 MINVALUE 1 START 1
CREATE TABLE categorie_coureur (
    id INT NOT NULL, 
    nom_categorie VARCHAR(155) NOT NULL, 
    PRIMARY KEY(id)
);

CREATE SEQUENCE equipe_id_seq INCREMENT BY 1 MINVALUE 1 START 1

CREATE TABLE equipe (
    id INT NOT NULL, 
    nom_equipe VARCHAR(155) NOT NULL, 
    PRIMARY KEY(id)
);

ALTER TABLE utilisateur ADD equipe_id INT DEFAULT NULL
ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B36D861B89 FOREIGN KEY (equipe_id) REFERENCES equipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE
CREATE UNIQUE INDEX UNIQ_1D1C63B36D861B89 ON utilisateur (equipe_id)

CREATE SEQUENCE coureur_id_seq INCREMENT BY 1 MINVALUE 1 START 1
CREATE TABLE coureur (
    id INT NOT NULL, 
    nom_coureur VARCHAR(155) NOT NULL, 
    numero_dossard VARCHAR(15) NOT NULL, 
    date_de_naissance DATE NOT NULL, 
    PRIMARY KEY(id)
);
ALTER TABLE coureur ADD equipe_id INT DEFAULT NULL
ALTER TABLE coureur ADD CONSTRAINT FK_8CCBA7496D861B89 FOREIGN KEY (equipe_id) REFERENCES equipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE
CREATE INDEX IDX_8CCBA7496D861B89 ON coureur (equipe_id)
ALTER TABLE coureur ALTER COLUMN equipe_id SET NOT NULL;
ALTER TABLE coureur ADD genre INT DEFAULT NULL
ALTER TABLE coureur ALTER COLUMN genre SET NOT NULL;

ALTER TABLE coureur ALTER equipe_id DROP NOT NULL
ALTER TABLE equipe ADD utilisateur_id INT DEFAULT NULL
ALTER TABLE equipe ADD CONSTRAINT FK_2449BA15FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE
CREATE UNIQUE INDEX UNIQ_2449BA15FB88E14F ON equipe (utilisateur_id)
ALTER TABLE utilisateur DROP CONSTRAINT fk_1d1c63b36d861b89
DROP INDEX uniq_1d1c63b36d861b89
ALTER TABLE utilisateur DROP equipe_id

CREATE TABLE coureur_categorie_coureur (
    coureur_id INT NOT NULL, 
    categorie_coureur_id INT NOT NULL, 
    PRIMARY KEY(coureur_id, categorie_coureur_id)
);
CREATE INDEX IDX_CAF43B33F4FA42E5 ON coureur_categorie_coureur (coureur_id)
CREATE INDEX IDX_CAF43B336A338849 ON coureur_categorie_coureur (categorie_coureur_id)
ALTER TABLE coureur_categorie_coureur ADD CONSTRAINT FK_CAF43B33F4FA42E5 FOREIGN KEY (coureur_id) REFERENCES coureur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE coureur_categorie_coureur ADD CONSTRAINT FK_CAF43B336A338849 FOREIGN KEY (categorie_coureur_id) REFERENCES categorie_coureur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE

CREATE SEQUENCE etape_coureur_id_seq INCREMENT BY 1 MINVALUE 1 START 1
CREATE TABLE etape_coureur (
    id INT NOT NULL, 
    coureur_id INT NOT NULL, 
    etape_course_id INT NOT NULL, 
    arrivee TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX IDX_D7A20492F4FA42E5 ON etape_coureur (coureur_id)
CREATE INDEX IDX_D7A20492740F7C7D ON etape_coureur (etape_course_id)
ALTER TABLE etape_coureur ADD CONSTRAINT FK_D7A20492F4FA42E5 FOREIGN KEY (coureur_id) REFERENCES coureur (id) NOT DEFERRABLE INITIALLY IMMEDIATE
ALTER TABLE etape_coureur ADD CONSTRAINT FK_D7A20492740F7C7D FOREIGN KEY (etape_course_id) REFERENCES etape_course (id) NOT DEFERRABLE INITIALLY IMMEDIATE
